In [2]:
# Sucessfully loop through all the pages and save in a CSV or a Sql lite DB
# Artist No1 - Steve Aoki 

import requests  
from bs4 import BeautifulSoup

# website_url = requests.get('http://www.steveaoki.com/tour-dates/all/archive-2016/').text
# website_url1 = requests.get('http://www.steveaoki.com/tour-dates/all/archive-2015/').text
# website_url2 = requests.get('http://www.steveaoki.com/tour-dates/all/archive-2014/').text
# website_url3 = requests.get('http://www.steveaoki.com/tour-dates/all/archive-2013/').text
# website_url4 = requests.get('http://www.steveaoki.com/tour-dates/all/archive-2012/').text
# website_url5 = requests.get('http://www.steveaoki.com/tour-dates/').text

all_urls = ['http://www.steveaoki.com/tour-dates/all/archive-2016/', 
            'http://www.steveaoki.com/tour-dates/all/archive-2015/',
            'http://www.steveaoki.com/tour-dates/all/archive-2014/',
            'http://www.steveaoki.com/tour-dates/all/archive-2013/',
            'http://www.steveaoki.com/tour-dates/all/archive-2012/',
            'http://www.steveaoki.com/tour-dates']
date1 = []
location1= []
for url  in all_urls:
#     You can access the url in this loop with the name 'url'
#     rest of your scraping code for a single page goes here
#     You also need to open your file in here
    website_url = requests.get(url).text
    soup = BeautifulSoup(website_url,'html.parser')
    artist_dates = soup.find_all('div', attrs={'class':'date_inner tour_archive_info'})
    for date in artist_dates:
    #  print(location.text())
   #    print(location.contents[0])
           date1.append(date.contents[2].strip())   
    artist_location=soup.find_all('div', class_='location_inner tour_archive_info')
# artist_location

    for location in artist_location:
    #  print(location.text())
   #    print(location.contents[0])
        location1.append(location.contents[0].strip())
# print (list(zip(date1,location1)))
print(len(date1))           
print(location1)   

    # print(soup.prettify())

444
['Cancun, Quintana Roo, Mexico', 'Puerto Vallarta, Mexico', 'Miami, FL, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Belen, Costa Rica', 'Las Vegas, NV, USA', 'Miami Gardens, FL, USA', 'Miami Beach, FL, USA', 'Las Vegas, NV, USA', 'Lansing, MI, USA', 'New York, NY, USA', 'Atlantic City, NJ, USA', 'Las Vegas, NV, USA', 'Lincoln, NE, USA', 'Tulsa, OK, USA', 'St. Charles, MO, USA', 'San Diego, CA, USA', 'Tampa, FL, USA', 'Seattle, WA, USA', 'Las Vegas, NV, USA', 'Panama City Beach, FL, USA', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'Austin, TX, USA', 'Amherst, MA, USA', 'Jacksonville, FL, USA', 'Danbury, CT, USA', 'Mashantucket, CT, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Reno, NV, USA', 'Las Vegas, NV, USA', 'New York, NY, USA', 'Las Vegas, NV, USA', 'Los Angeles, CA, USA', 'Mexico City, DF, Mexico', 'Atlantic City, NJ, USA', 'Atlanta, GA', 'Atlanta, GA, USA', 'Cambridge, MA, USA', 'Las Vegas, NV, USA', 'West Palm Beach, FL, USA', 'Las Vegas, NV, USA', 'Cleveland, OH, USA', 'Philadelphia, PA, USA', 'Santo Domingo, Dominican Republic', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Washington, DC, USA', 'Washington, D.C., USA', 'Chicago, IL, USA', 'Chicago, IL, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Chaguaramas, Trinidad & Tobago', 'Las Vegas, NV, USA', 'Lake Buena Vista, FL, USA', 'San Luis Potosi, SLP, Mexico', 'Hidalgo, TX, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Toronto, ON, Canada', 'Las Vegas, NV, USA', 'Somerset, WI, USA', 'Las Vegas, NV, USA', 'Scottsdale, AZ, USA', 'Las Vegas, NV, USA', 'New York, NY, USA', 'Las Vegas, NV, USA', 'Del Mar, CA, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Denver, CO, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'San Salvador, El Salvador', 'Playa del Carmen, Mexico', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Edmonton, AB, Canada', 'Miami Beach, FL, USA', 'Phoenix, AZ, USA', 'Austin, TX, USA', 'Houston, TX, USA', 'Las Vegas, NV, USA', 'El Paso, TX, USA', 'Tucson, AZ, USA', 'Scottsdale, AZ, USA', 'San Diego, CA, USA', 'Old San Juan, Puerto Rico', 'Pasadena, CA, USA', 'Salt Lake City, UT, USA', 'Denver, CO, USA', 'Kansas City, MO, USA', 'Saint Paul, MN, USA', 'Chicago, IL, USA', 'Chicago, IL, USA', 'Royal Oak, MI, USA', 'Saint Louis, MO, USA', 'Toronto, ON, Canada', 'Las Vegas, NV, USA', 'Montreal, QC, Canada', 'Montreal, QC, Canada', 'Atlantic City, NJ, USA', 'Rochester, NY, USA', 'Wallingford, CT, USA', 'New York, NY, USA', 'New York, NY, USA', 'Mashantucket, CT, USA', 'El Paso, TX, USA', 'Cancun, Quintana Roo, Mexico', 'Boston, MA, USA', 'South Padre Island, TX, USA', 'Austin, TX, USA', 'Charlotte, NC, USA', 'Norfolk, VA, USA', 'Washington, DC, USA', 'TBA, TBA, USA', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'Las Vegas, NV, USA', 'Miami, FL, USA', 'Cancun, Quintana Roo, Mexico', 'Puerto Vallarta, Mexico', 'Oakland, CA, USA', 'Concord, NH, USA', 'University Park, PA, USA', 'Philadelphia, PA, USA', 'Las Vegas, NV, USA', 'Queretaro, Mexico', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Atlanta, GA, USA', 'Hollywood, FL, USA', 'Las Vegas, NV, USA', 'New York, NY, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Columbus, OH, USA', 'New Orleans, LA, USA', 'Indianapolis, IN, USA', 'Miami Beach, FL, USA', 'Dover, DE, USA', 'Las Vegas, NV, USA', 'Boston, MA, USA', 'Las Vegas, NV, USA', 'San Diego, CA, USA', 'Toronto, ON, Canada', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Los Angeles, CA, USA', 'Las Vegas, NV, USA', 'Seattle, WA, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Chicago, IL, USA', 'Chicago, IL, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Tucson, AZ, USA', 'St. Petersburg, FL, USA', 'Syracuse, NY, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Milwaukee, WI, USA', 'Las Vegas, NV, USA', 'Tijuana, BC, Mexico', 'Houston, TX, USA', 'Detroit, MI, USA', 'San Diego, CA, USA', 'Calgary, AB, Canada', 'Mashantucket, CT, USA', 'Mashantucket, CT, USA', 'Las Vegas, NV, USA', 'Monterrey, Nuevo León, Mexico', 'Mexico City, Mexico', 'Guadalajara, Mexico', 'Scottsdale, AZ, USA', 'Reno, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Miami Beach, FL, USA', 'Miami, FL, USA', 'Las Vegas, NV, USA', 'Brooklyn, NY, USA', 'Las Vegas, NV, USA', 'San Antonio, TX, USA', 'Acapulco, Gro, Mexico', 'Playa Del Carmen, Riviera Maya, Mexico', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'Honolulu, HI, USA', 'Park City, UT, USA', 'San Jose, CA, USA', 'San Luis Obispo, CA, USA', 'Scottsdale, AZ, USA', 'Atlantic City, NJ, USA', 'Miami Beach, FL, USA', 'Las Vegas, NV, USA', 'South Padre Island, TX, USA', 'Panama City Beach, FL, USA', 'Austin, TX, USA', 'Toluca, Mexico', 'Sacramento, CA, USA', 'Las Vegas, NV, USA', 'San Francisco, CA, USA', 'Houston, TX, USA', 'El Paso, TX, USA', 'Winston-Salem, NC, USA', 'Atlantic City, NJ, USA', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'London, ONT, Canada', 'Fairfield, CT, USA', 'Nashville, TN, USA', 'Mexico City, DF, Mexico', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Hollywood, FL, USA', 'Playa Blanca Farallon, COCLE, Panama, Panama', 'Miami Beach, FL, USA', 'Las Vegas, NV, USA', 'Ottawa, ON, Canada', 'Towson, MD, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Miami Beach, FL, USA', 'Winnipeg, MB, Canada', 'Montreal, QC, Canada', 'Las Vegas, NV, USA', 'Tacoma, WA, USA', 'Toronto, ON, Canada', 'Las Vegas, NV, USA', 'Bethel, NY, USA', 'Atlantic City, NJ, USA', 'Las Vegas, NV, USA', 'Chicago, IL, USA', 'Chicago, IL, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Washington, DC, USA', 'Tegucigalpa, Honduras', 'Belen, Costa Rica', 'Miami Beach, FL, USA', 'Atlantic City, NJ, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'New York, NY, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Del Mar, CA, USA', 'Philadelphia, PA, USA', 'Los Angeles, CA, USA', 'Atlantic City, NJ, USA', 'Las Vegas, NV, USA', 'Fairburn, GA, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Eugene, OR, USA', 'Milwaukee, WI, USA', 'Minneapolis, MN, USA', 'Santa Clara, CA, USA', 'Las Vegas, NV, USA', 'Miami, FL, USA', 'San Diego, CA, USA', 'San Jose, CA, USA', 'Los Angeles, CA, USA', 'Magna, UT, USA', 'Las Vegas, NV, USA', 'Philadelphia, PA, USA', 'Las Vegas, NV, USA', 'Orlando, FL, USA', 'Las Vegas, NV, USA', 'Ledyard, CT, USA', 'Atlantic City, NJ, USA', 'Las Vegas, NV, USA', 'Tempe, AZ, USA', 'Miami Beach, FL, USA', 'Punta Cana, Dominican Republic', 'Toronto, ON, Canada', 'Toronto, ON, Canada', 'Las Vegas, NV, USA', 'Acapulco, Gro, Mexico', 'Miami Beach, FL, USA', 'Vancouver, BC, Canada', 'Cancun, Quintana Roo, Mexico', 'Winnipeg, MB, Canada', 'Winnipeg, MB, Canada', 'Saskatoon, SK, Canada', 'Edmonton, AB, Canada', 'Edmonton, AB, Canada', 'Lethbridge, AB, Canada', 'Las Vegas, NV, USA', 'Waikiki, HI, USA', 'Honolulu, HI, USA', 'Verona, NY, USA', 'New Orleans, LA, USA', 'Atlantic City, NJ, USA', 'Chihuahua, Mexico', 'Monterrey - Nuevo León, Mexico', 'Scottsdale, AZ, USA', 'Los Angeles, CA, USA', 'Panama City, Panama', 'Guadalajara, Jalisco, Mexico', 'Miami, FL, USA', 'Miami Beach, FL, USA', 'Miami Beach, FL, USA', 'Miami, FL, USA', 'Atlantic City, NJ, USA', 'San Juan del Sur, Rivas, Nicaragua', 'Orlando, FL, USA', 'Columbus, OH, USA', 'Rochester, MI, USA', 'Athens, OH, USA', 'Buffalo, NY, USA', 'Saint Louis, MO, USA', 'Kent, OH, USA', 'Storrs, CT, USA', 'Babson Park, MA, USA', 'Lowell, MA, USA', 'Boston, MA, USA', 'Atlantic City, NJ, USA', 'Durham, NC, USA', 'Las Vegas, NV, USA', 'New Britain, CT, USA', 'Cortland, NY, USA', 'Las Vegas, NV, USA', 'San Francisco, CA, USA', 'Houston, TX, USA', 'Miami Beach, FL, USA', 'Las Vegas, NV, USA', 'Gulf Shores, AL, USA', 'Atlantic City, NJ, USA', 'New York, NY, USA', 'Quincy, MA, USA', 'Tampa, FL, USA', 'Las Vegas, NV, USA', 'Scottsdale, AZ, USA', 'George, WA, USA', 'Charlotte, NC, USA', 'Las Vegas, NV, USA', 'Torreon, COA, Mexico', 'San Diego, CA, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Miami Beach, FL, USA', 'Las Vegas, NV, USA', 'Hidalgo, TX, USA', 'Calgary, AB, Canada', 'Atlantic City, NJ, USA', 'Santa Domingo, Dominican Republic', 'Chicago, IL, USA', 'Chicago, IL, USA', 'Toronto, ON, Canada', 'Toronto, ONT, Canada', 'Las Vegas, NV, USA', 'Atlantic City, NJ, USA', 'Atlantic City, NJ, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Mexico City, DF, Mexico', 'El Paso, TX, USA', 'New York, NY, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Fairburn, GA, USA', 'Fairburn, GA, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'Chicago, IL, USA', 'Las Vegas, NV, USA', 'Las Vegas, NV, USA', 'East Lansing, MI, USA', 'Las Vegas, NV, USA', 'Atlantic City, NJ, USA', 'Austin, TX, USA', 'Dallas, TX, USA', 'Corpus Christi, TX, USA', 'Houston, TX, USA', 'Allendale, MI, USA', 'Miami Beach, FL, USA', 'Tampa, FL, USA', 'Orlando, FL, USA', 'Norfolk, VA, USA', 'Philadelphia, PA, USA', 'Columbia, MD, USA', 'Nashville, TN, USA', 'Wallingford, CT, USA', 'Toronto, ON, Canada', 'Montreal, QC, Canada', 'Boston, MA, USA', 'New York, NY, USA', 'New York, NY, USA', 'Rochester, NY, USA', 'Columbus, OH, USA', 'Detroit, MI, USA', 'Saint Louis, MO, USA', 'Milwaukee, WI, USA', 'Las Vegas, NV, USA', 'Minneapolis, MN, USA', 'Saskatoon, SK, Canada', 'Winnipeg, MB, Canada', 'Denver, CO, USA', 'Salt Lake City, UT, USA', 'Los Angeles, CA, USA', 'San Francisco, CA, USA', 'San Francisco, CA, USA', 'Portland, OR, USA', 'Seattle, WA, USA', 'Vernon, BC, Canada', 'Edmonton, AB, Canada', 'Vancouver, BC, Canada', 'TBA, TBA, USA', 'Las Vegas, NV, USA', 'Miami Beach, FL, USA', 'New York, NY, USA', 'Aspen, CO, USA', 'Punta Cana, Dominican Republic', 'Miami Gardens, FL, USA', 'Las Vegas, NV, USA', 'Puerto de San Jose, Guatemala', 'San Salvador, El Salvador', 'Acapulco Diamante, GRO., Mexico', 'Cancun, Quintana Roo, Mexico', 'San Juan, Puerto Rico', 'New York, NY, USA', 'San Francisco, CA, USA', 'San Francisco, CA, USA', 'Montreal, QC, Canada', 'Atlantic City, NJ, USA']

In [3]:
# date1 = []
# artist_dates = soup.find_all('div', attrs={'class':'date_inner tour_archive_info'})
# print(artist_dates.contents[2])

# for date in artist_dates:
#    # print((date).get_text())
#      date1.append(date)
# print(date1)

In [4]:
# date1 = []
# location1 = []

# artist_dates = soup.find_all('div', attrs={'class':'date_inner tour_archive_info'})
# # print(artist_dates.contents[2])

# for date in artist_dates:
#     #print(date)
#     date1.append(date.contents[2])
# print(date1)    
    
# artist_location=soup.find_all('div', class_='location_inner tour_archive_info')
# # artist_location

# for location in artist_location:
#     #  print(location.text())
#    #    print(location.contents[0])
#        location1.append(location.contents[0])
# location1

# for date in artist_dates:
#     print(date.contents[0])
#     date1.append(date.contents[0])

In [5]:
import pandas as pd

test_df = pd.DataFrame({'venue': location1
                        })
print(test_df.info())
test_df

test_df1 = pd.DataFrame({'timeframe': date1
                        })
print(test_df1.info())
test_df1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 1 columns):
venue    444 non-null object
dtypes: object(1)
memory usage: 3.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 1 columns):
timeframe    444 non-null object
dtypes: object(1)
memory usage: 3.5+ KB
None

        timeframe
0     Jan 1, 2016
1     Jan 2, 2016
2     Jan 3, 2016
3     Jan 6, 2016
4     Jan 8, 2016
5     Jan 9, 2016
6    Jan 15, 2016
7    Jan 16, 2016
8    Jan 16, 2016
9    Jan 22, 2016
10   Jan 23, 2016
11   Jan 28, 2016
12   Jan 29, 2016
13   Jan 30, 2016
14   Feb 26, 2016
15   Feb 26, 2016
16   Feb 27, 2016
17    Mar 4, 2016
18    Mar 5, 2016
19   Mar 12, 2016
20   Mar 13, 2016
21   Mar 15, 2016
22   Mar 16, 2016
23   Mar 16, 2016
24   Mar 17, 2016
25   Mar 19, 2016
26   Mar 31, 2016
27    Apr 1, 2016
28    Apr 2, 2016
29    Apr 2, 2016
..            ...
414  Nov 10, 2013
415  Nov 11, 2013
416  Nov 12, 2013
417  Nov 13, 2013
418  Nov 15, 2013
419  Nov 16, 2013
420  Nov 16, 2013
421  Nov 19, 2013
422  Nov 20, 2013
423  Nov 21, 2013
424  Nov 22, 2013
425  Nov 23, 2013
426  Nov 23, 2013
427  Nov 24, 2013
428  Nov 27, 2013
429  Dec 19, 2013
430  Dec 21, 2013
431  Dec 26, 2013
432  Dec 27, 2013
433  Dec 27, 2013
434  Dec 28, 2013
435  Dec 29, 2013
436  Dec 30, 2013
437  Dec 31, 2013
438  Oct 27, 2012
439  Dec 27, 2012
440  Dec 29, 2012
441  Dec 29, 2012
442  Dec 30, 2012
443  Dec 31, 2012

[444 rows x 1 columns]

In [6]:
final = test_df['venue'].str.split(', ', 2, expand=True)
final.columns =['City', 'State', 'Country']
final

                   City               State Country
0                Cancun        Quintana Roo  Mexico
1       Puerto Vallarta              Mexico    None
2                 Miami                  FL     USA
3             Las Vegas                  NV     USA
4             Las Vegas                  NV     USA
5                 Belen          Costa Rica    None
6             Las Vegas                  NV     USA
7         Miami Gardens                  FL     USA
8           Miami Beach                  FL     USA
9             Las Vegas                  NV     USA
10              Lansing                  MI     USA
11             New York                  NY     USA
12        Atlantic City                  NJ     USA
13            Las Vegas                  NV     USA
14              Lincoln                  NE     USA
15                Tulsa                  OK     USA
16          St. Charles                  MO     USA
17            San Diego                  CA     USA
18                Tampa                  FL     USA
19              Seattle                  WA     USA
20            Las Vegas                  NV     USA
21    Panama City Beach                  FL     USA
22          Miami Beach                  FL     USA
23          Miami Beach                  FL     USA
24          Miami Beach                  FL     USA
25               Austin                  TX     USA
26              Amherst                  MA     USA
27         Jacksonville                  FL     USA
28              Danbury                  CT     USA
29         Mashantucket                  CT     USA
..                  ...                 ...     ...
414           Saskatoon                  SK  Canada
415            Winnipeg                  MB  Canada
416              Denver                  CO     USA
417      Salt Lake City                  UT     USA
418         Los Angeles                  CA     USA
419       San Francisco                  CA     USA
420       San Francisco                  CA     USA
421            Portland                  OR     USA
422             Seattle                  WA     USA
423              Vernon                  BC  Canada
424            Edmonton                  AB  Canada
425           Vancouver                  BC  Canada
426                 TBA                 TBA     USA
427           Las Vegas                  NV     USA
428         Miami Beach                  FL     USA
429            New York                  NY     USA
430               Aspen                  CO     USA
431          Punta Cana  Dominican Republic    None
432       Miami Gardens                  FL     USA
433           Las Vegas                  NV     USA
434  Puerto de San Jose           Guatemala    None
435        San Salvador         El Salvador    None
436   Acapulco Diamante                GRO.  Mexico
437              Cancun        Quintana Roo  Mexico
438            San Juan         Puerto Rico    None
439            New York                  NY     USA
440       San Francisco                  CA     USA
441       San Francisco                  CA     USA
442            Montreal                  QC  Canada
443       Atlantic City                  NJ     USA

[444 rows x 3 columns]

In [7]:
final_df = pd.concat([final, test_df1], axis = 1)
final_df

                   City               State Country     timeframe
0                Cancun        Quintana Roo  Mexico   Jan 1, 2016
1       Puerto Vallarta              Mexico    None   Jan 2, 2016
2                 Miami                  FL     USA   Jan 3, 2016
3             Las Vegas                  NV     USA   Jan 6, 2016
4             Las Vegas                  NV     USA   Jan 8, 2016
5                 Belen          Costa Rica    None   Jan 9, 2016
6             Las Vegas                  NV     USA  Jan 15, 2016
7         Miami Gardens                  FL     USA  Jan 16, 2016
8           Miami Beach                  FL     USA  Jan 16, 2016
9             Las Vegas                  NV     USA  Jan 22, 2016
10              Lansing                  MI     USA  Jan 23, 2016
11             New York                  NY     USA  Jan 28, 2016
12        Atlantic City                  NJ     USA  Jan 29, 2016
13            Las Vegas                  NV     USA  Jan 30, 2016
14              Lincoln                  NE     USA  Feb 26, 2016
15                Tulsa                  OK     USA  Feb 26, 2016
16          St. Charles                  MO     USA  Feb 27, 2016
17            San Diego                  CA     USA   Mar 4, 2016
18                Tampa                  FL     USA   Mar 5, 2016
19              Seattle                  WA     USA  Mar 12, 2016
20            Las Vegas                  NV     USA  Mar 13, 2016
21    Panama City Beach                  FL     USA  Mar 15, 2016
22          Miami Beach                  FL     USA  Mar 16, 2016
23          Miami Beach                  FL     USA  Mar 16, 2016
24          Miami Beach                  FL     USA  Mar 17, 2016
25               Austin                  TX     USA  Mar 19, 2016
26              Amherst                  MA     USA  Mar 31, 2016
27         Jacksonville                  FL     USA   Apr 1, 2016
28              Danbury                  CT     USA   Apr 2, 2016
29         Mashantucket                  CT     USA   Apr 2, 2016
..                  ...                 ...     ...           ...
414           Saskatoon                  SK  Canada  Nov 10, 2013
415            Winnipeg                  MB  Canada  Nov 11, 2013
416              Denver                  CO     USA  Nov 12, 2013
417      Salt Lake City                  UT     USA  Nov 13, 2013
418         Los Angeles                  CA     USA  Nov 15, 2013
419       San Francisco                  CA     USA  Nov 16, 2013
420       San Francisco                  CA     USA  Nov 16, 2013
421            Portland                  OR     USA  Nov 19, 2013
422             Seattle                  WA     USA  Nov 20, 2013
423              Vernon                  BC  Canada  Nov 21, 2013
424            Edmonton                  AB  Canada  Nov 22, 2013
425           Vancouver                  BC  Canada  Nov 23, 2013
426                 TBA                 TBA     USA  Nov 23, 2013
427           Las Vegas                  NV     USA  Nov 24, 2013
428         Miami Beach                  FL     USA  Nov 27, 2013
429            New York                  NY     USA  Dec 19, 2013
430               Aspen                  CO     USA  Dec 21, 2013
431          Punta Cana  Dominican Republic    None  Dec 26, 2013
432       Miami Gardens                  FL     USA  Dec 27, 2013
433           Las Vegas                  NV     USA  Dec 27, 2013
434  Puerto de San Jose           Guatemala    None  Dec 28, 2013
435        San Salvador         El Salvador    None  Dec 29, 2013
436   Acapulco Diamante                GRO.  Mexico  Dec 30, 2013
437              Cancun        Quintana Roo  Mexico  Dec 31, 2013
438            San Juan         Puerto Rico    None  Oct 27, 2012
439            New York                  NY     USA  Dec 27, 2012
440       San Francisco                  CA     USA  Dec 29, 2012
441       San Francisco                  CA     USA  Dec 29, 2012
442            Montreal                  QC  Canada  Dec 30, 2012
443       Atlantic City                  NJ     USA  Dec 31, 2012

[444 rows x 4 columns]

In [35]:
city_list = set(final_df['City'].tolist())
len(city_list)

146

In [16]:
import gmplot
from config import gkey
import gmaps
import re
from pprint import pprint
from sodapy import Socrata
import numpy as np
from IPython.display import Image
%matplotlib inline

In [33]:
latitude = []
longitude = []

geo_location = {}

for city in city_list:
    target_url = f"https://maps.googleapis.com/maps/api/geocode/json?" \
            f"address={city}&key={gkey}"
    try:
        #import pdb; pdb.set_trace()

        geo_data = requests.get(target_url).json() 
        lat = geo_data["results"][0]["geometry"]["location"]["lat"]
        lng = geo_data["results"][0]["geometry"]["location"]["lng"]
        latitude.append(lat)
        longitude.append(lng)
    except Exception as exp:
        print(f"ERROR2:{exp}, {geo_data}")
        lat = ""
        lng = ""
#     geo_location["lat"] = lat
#     geo_location['lng'] = lng
#     geo_location['city'] = city

KeyboardInterrupt:

In [31]:
geo_location

{'city': 'Atlantic City', 'lat': 39.3642834, 'lng': -74.4229266}

In [27]:
# geocode_df = pd.DataFrame(geo_location)
# geocode_df

# pd.DataFrame(geo_location.items(), columns=['Place', 'Lat', 'Lng'])

geo_df = pd.DataFrame.from_dict({"lat":latitude, "lng":longitude,"city":city_list})
geo_df

            city        lat        lng
0  Atlantic City  39.364283 -74.422927